name: Build Samples

on:
  workflow_call:

jobs:
  Hello-World-APP:
    name: Hello World App
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: corepack yarn install

      - name: Build Hello World App
        run: corepack yarn build

      - name: Test Hello World App
        run: corepack yarn test
